name = "autoclean-eeg-config"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[env.production]
name = "autoclean-eeg-config-production"

[env.preview]
name = "autoclean-eeg-config-preview"